name: Android
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      - run: |
          which corepack
          corepack enable
          cd example && yarn install

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            .gradle
            example/android/.gradle
          key: gradle

      - name: Build android example app
        run: yarn build:android
