name: 'Check signed commits in PR'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
permissions:
  contents: read
  pull-requests: write
jobs:
  main:
    name: Check signed commits in PR
    uses: evva-sfw/workflows/.github/workflows/call_signedPrCheck.yml@main
