# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    - run: yarn test

  test-ios:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [lts/*]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: "Get Ruby Version"
        run: ruby --version
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "5.10.0"
      - name: Get Swift Version
        run: swift --version
      - name: Set Swift Version
        if: runner.os == 'macOS'
        run: xcrun --toolchain ${{ env.TOOLCHAINS }} swift --version
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
      - name: Get Xcode version
        run: xcodebuild -version
      - name: Show available software
        run: softwareupdate --list --all
#      - run: corepack enable
#      - run: yarn
#      - run: cd example; bundle; cd -
#      - run: cd example/ios; bundle exec pod install; cd -
#      - run: make test
