# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Test
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
      - run: yarn
      - run: yarn test

  test-ios:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [lts/*]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: 'Get Ruby Version'
        run: ruby --version
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: '5.10.0'
      - name: Get Swift Version
        run: swift --version
      - name: Get Xcode version
        env:
          DEVELOPER_DIR: /Applications/Xcode_15.4.app
        run: xcodebuild -version
      - name: Cache Pods
        id: cache-test-ios-pods
        uses: actions/cache@v4
        with:
          path: |
            example/ios/Pods
          key: cache-test-ios-pods
      - name: Cache node_modules
        id: cache-test-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            example/node_modules
          key: cache-test-node-modules
      - name: Cache Xcode DerivedData
        uses: irgaly/xcode-cache@v1.7.2
        with:
          key: cache-test-xcode-deriveddata-${{ github.workflow }}-${{ github.sha }}
          restore-keys: cache-test-xcode-deriveddata-${{ github.workflow }}-
      - run: corepack enable
      - run: yarn
      - run: cd example; bundle; cd -
      - run: cd example/ios; bundle exec pod install; cd -
      - name: Run Tests
        env:
          DEVELOPER_DIR: /Applications/Xcode_15.4.app
        run: make test-ios

  test-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Cache node_modules
        id: cache-test-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            example/node_modules
          key: cache-test-node-modules
      - name: Cache Gradle
        id: cache-test-android-gradle
        uses: actions/cache@v4
        with:
          path: |
            .gradle
            example/android/.gradle
          key: ${{ runner.os }}_cache-test-android-gradle
      - run: |
          corepack enable
          yarn
      - name: Run Gradle
        if: steps.cache-gradle.outputs.cache-hit != 'true'
        run: example/android/gradlew
      - name: Run Tests
        run: make test-android
