name: Update Changelog on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0 
          with:
            fetch-depth: 0 # For release-it and auto-changelog to be able to generate the full changelog
            fetch-tags: true
            token: ${{ secrets.BOT_SSH_PRIVATE_KEY }}
            ref: main

        - name: Setup Node.js
          uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
          with:
            node-version: lts/*

        - name: Install node dependencies
          run: npm ci

        - name: Generate changelog
          run: |
            npx auto-changelog -c .auto-changelog
            cat CHANGELOG.md

        - name: Commit & Push changes
          uses: iarekylew00t/verified-bot-commit@126a6a11889ab05bcff72ec2403c326cd249b84c # v2.3.0
          with:
            ref: main 
            token: ${{ secrets.BOT_GITHUB_TOKEN }}
            message: "docs: Updated changelog"
            files: |
              CHANGELOG.md